export const RETRIEVE_ALL_POSTS = 'RETRIEVE_ALL_POSTS';
export const RETRIEVE_SPECIFIC_USER_POSTS = 'RETRIEVE_SPECIFIC_USER_POSTS';
export const RETRIEVE_SPECIFIC_POST = 'RETRIEVE_SPECIFIC_POST';
export const REPLACE_POST = 'REPLACE_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const CREATE_POST = 'CREATE_POST';
export const DELETE_POST = 'DELETE_POST';
